// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2011-2020 ETH Zurich.

package viper.server.core

import viper.server.vsi.{JobNotFoundException, VerJobId}
import viper.silver.reporter.{Message, OverallFailureMessage, OverallSuccessMessage}
import viper.silver.verifier.{VerificationResult, Failure => VerificationFailure, Success => VerificationSuccess}

import scala.concurrent.Future

object ViperCoreServerUtils {

  /** Get a Future containing all messages generated by the backend.
    *
    * Deletes the jobHandle on completion.
    */
  def getMessagesFuture(core: ViperCoreServer, jid: VerJobId)(implicit executor: VerificationExecutionContext): Future[List[Message]] = {
    core.collectMessages(jid).getOrElse(Future.failed(JobNotFoundException))
  }

  /** Get a Future containing only verification results.
    *
    * Deletes the jobHandle on completion.
    */
  def getResultsFuture(core: ViperCoreServer, jid: VerJobId)(implicit executor: VerificationExecutionContext): Future[VerificationResult] = {
    val messages_future = getMessagesFuture(core, jid)
    val result_future: Future[VerificationResult] = messages_future.map(msgs => {
      // note that errors cannot be extracted from entity failure messages because some backends (e.g. Carbon) do not
      // produce entity messages but only an overall message at the very end
      val overallResults = msgs.collect {
        case _: OverallSuccessMessage => VerificationSuccess
        case m: OverallFailureMessage => VerificationFailure(m.result.errors)
      }
      assert(overallResults.length == 1, s"every verification should result in exactly one overall success or failure message but got $msgs")
      overallResults.head
    })
    result_future
  }
}
