// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.
//
// Copyright (c) 2011-2020 ETH Zurich.

package viper.server.vsi


/** This trait is a generic wrapper for Messages generated by backends. It must be extended in
  * order to specify what types of messages the client uses.
  * */
trait Envelope

sealed trait Post {
  type A
}

trait Packer extends Post {

  /** Must be implemented to map client-specific messages to Envelopes.
    * */
  def pack(m: A): Envelope
}

trait Unpacker extends Post {

  /** Must be implemented to map Envelopes to client-specific messages.
    * */
  def unpack(m: Envelope): A
}